actions = {
  'a': ('brightness', 'set'),
  'b': ('brightness', 'plus'),
  'c': ('brightness', 'minus'),
  'd': ('brightness', 'clear'),
  'e': ('red', 'set'),
  'f': ('red', 'plus'),
  'g': ('red', 'minus'),
  'h': ('red', 'clear'),
  'i': ('green', 'set'),
  'j': ('green', 'plus'),
  'k': ('green', 'minus'),
  'l': ('green', 'clear'),
  'm': ('blue', 'set'),
  'n': ('blue', 'plus'),
  'o': ('blue', 'minus'),
  'p': ('blue', 'clear'),
  'q': ('white', 'set'),
  'r': ('white', 'plus'),
  's': ('white', 'minus'),
  't': ('white', 'clear'),
  'u': ('pixel', 'set'),
  'v': ('pixel', 'plus'),
  'w': ('pixel', 'minus'),
  'x': ('pixel', 'clear'),
  'y': ('hue', 'set'),
  'z': ('hue', 'plus'),
  'A': ('hue', 'minus'),
  'B': ('hue', 'clear'),
  'C': ('func', 'draw'),
  'D': ('func', 'save'),
  'E': ('func', 'restore'),
  'F': ('func', 'run'),
  'G': ('func', 'noop'),
}

codes = dict(map(reversed, actions.items()))
